rootProject.name = "kuberig-dsl-openshift"

include("kuberig-dsl-openshift-v3.6.0-rc.0")
include("kuberig-dsl-openshift-v3.6.0")
include("kuberig-dsl-openshift-v3.6.1")
include("kuberig-dsl-openshift-v3.7.0-alpha.0")
include("kuberig-dsl-openshift-v3.7.0-alpha.1")
include("kuberig-dsl-openshift-v3.7.0-rc.0")
include("kuberig-dsl-openshift-v3.7.0")
include("kuberig-dsl-openshift-v3.7.1")
include("kuberig-dsl-openshift-v3.7.2")
include("kuberig-dsl-openshift-v3.8.0-alpha.0")
include("kuberig-dsl-openshift-v3.8.0-alpha.1")
include("kuberig-dsl-openshift-v3.8.0")
include("kuberig-dsl-openshift-v3.9.0-alpha.0")
include("kuberig-dsl-openshift-v3.9.0-alpha.1")
include("kuberig-dsl-openshift-v3.9.0-alpha.2")
include("kuberig-dsl-openshift-v3.9.0-alpha.3")
include("kuberig-dsl-openshift-v3.9.0-alpha.4")
include("kuberig-dsl-openshift-v3.9.0")
include("kuberig-dsl-openshift-v3.10.0-alpha.0")
include("kuberig-dsl-openshift-v3.10.0-rc.0")
include("kuberig-dsl-openshift-v3.10.0")
include("kuberig-dsl-openshift-v3.11.0-alpha.0")
include("kuberig-dsl-openshift-v3.11.0")
include("kuberig-dsl-openshift-v4.0.0-alpha.0")