# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

workflows:
  upstream-and-availability-sync:
    jobs:
      - upstream-and-availability-sync:
          context:
            - kuberig-context
            - docker-hub-creds
  upstream-and-availability-sync-scheduled:
    triggers:
      - schedule:
          # https://crontab.guru/#0_0-23_*_*_*
          # every hour
          cron: "0 0-23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - upstream-and-availability-sync:
          context:
            - kuberig-context
            - docker-hub-creds

jobs:
  upstream-and-availability-sync:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:70:df:15:cb:13:fa:db:af:c1:b0:79:31:11:c8:db"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      # detect upstream versions and publish them to bintray
      - run: |
          ./gradlew generateDslProjects publishMissing showMissingFromJCenter $GRADLE_ARGS
          changed_files=$(git status --porcelain --untracked-files=no | wc -l)
          if [ $changed_files -gt 0 ]; then
            git config user.name "circleci"
            git config user.email "circleci@rigel.dev"
            git add --all
            git commit -m "upstream sync [skip ci]"
            git push origin <<pipeline.git.branch>>
          else
            echo "No changes to commit";
          fi;
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - store_artifacts:
          path: build/libs